// Manual explore walkthrough on the live stack (keyboard only after load): screenshots of each tool.
import { chromium } from '@playwright/test';
const repo = process.argv[2] ?? 'pallets/flask';
const out = process.argv[3] ?? 'shots';
const browser = await chromium.launch({ args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 900 } });
const problems = [];
page.on('console', (m) => m.type() === 'error' && problems.push(m.text()));
page.on('pageerror', (e) => problems.push(e.message));
await page.goto('https://localhost:8443/#explore');
await page.fill('#repoInput', repo);
await page.keyboard.press('Enter');
await page.waitForSelector('body.mode-city', { timeout: 120000 });
await page.waitForTimeout(1500);
const shot = async (n) => { await page.waitForTimeout(1300); await page.screenshot({ path: `${out}/x-${n}.png` }); };
await page.keyboard.press('i'); await shot('insights');
await page.keyboard.press('i'); await page.keyboard.press('m'); await page.keyboard.press('/');
await page.keyboard.type('flask/app'); await page.waitForTimeout(300); await shot('palette');
await page.keyboard.press('Enter'); await shot('inspector');
await page.keyboard.press('Escape'); await page.keyboard.press('3'); await shot('topdown');
await page.keyboard.press('1'); await page.keyboard.press('c'); await shot('compare');
await page.keyboard.press('Escape'); await page.keyboard.press('?'); await shot('help');
await page.keyboard.press('Escape'); await page.keyboard.press('2'); await shot('street');
console.log('problems', JSON.stringify(problems));
await browser.close();
